### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by kskotenko** [kskotenko/homepage#3]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by kse-kot** [comment]
Do not give up on the person you are becoming - it is a phrase that encourages my inner motivation at the moment. I feel it is time something changed in my life, and I believe it is something good and inspiring. I take this Binary course for the 4th time already, and you might think I am a loser trying and trying again with no success. BUT I know what goals I am following and what I need these Binary tasks for. 

“Fall down seven times, stand up eight.”
