### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by kskotenko** [kskotenko/homepage#4]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by kse-kot** [comment]
https://www.linkedin.com/in/kseniya-kotenko/
https://www.instagram.com/kse_kot/
kskotenko@gmail.com
https://t.me/kse_kot
https://github.com/kskotenko
